version: '3.7'
services:
  mariadb:
    image: ${REGISTRY_HOST}/${DOLI_DB_HOST}:latest 
    build: 
      context: ./bin/${DOLI_DB_HOST}
    ports:
      - "${LOCAL_DB_PORT}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_DATABASE: ${DOLI_DB_NAME}
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      
  web:
    image: ${REGISTRY_HOST}/mydolibarr10:latest
    build:
      context: ./bin/${DOLI_VERSION}
    environment:
        DOLI_INSTALL_AUTO: ${DOLI_INSTALL_AUTO}
        DOLI_DB_HOST: ${DOLI_DB_HOST}
        DOLI_DB_USER: ${DOLI_DB_USER}
        DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
        DOLI_DB_NAME: ${DOLI_DB_NAME}
        DOLI_URL_ROOT: 'http://0.0.0.0'
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        
    ports:
        - "${LOCAL_PORT}:80"
    links:
        - mariadb
    volumes:
      - ${DOCUMENT_ROOT_HTML}:/var/www/html
      - ${DOCUMENT_ROOT_DOC}:/var/www/documents
      - ${DOCUMENT_ROOT_SCRIPTS}:/var/www/scripts
